### ISSUE TITLE
`rosdep install` fails due to missing definition for `rtklib_msgs` and `llh_converter`

### ISSUE THREAD

**Issue by mojomex** [tier4/edge-auto#23]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

Currently, a clean install of Edge.Auto does not build because of the following error during `rosdep install`:

```shell
~/edge-auto$ rosdep install --ignore-src --from src
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
eagleye_msgs: Cannot locate rosdep definition for [rtklib_msgs]
eagleye_navigation: Cannot locate rosdep definition for [rtklib_msgs]
eagleye_geo_pose_converter: Cannot locate rosdep definition for [llh_converter]
eagleye_rt: Cannot locate rosdep definition for [rtklib_msgs]
eagleye_gnss_converter: Cannot locate rosdep definition for [rtklib_msgs]
```

### Expected behavior

Edge.Auto builds

### Actual behavior

Build fails

### Steps to reproduce

Build from scratch following the Autoware documentation

### Versions

Ubuntu 22.04 
ROS 2 Hubmle

### Possible causes

Searching for the issue online, the [Autoware documentation](https://autowarefoundation.github.io/autoware-documentation/main/how-to-guides/integrating-autoware/launch-autoware/localization/eagleye/#dependencies) states that the following dependencies are necessary in `autoware.repos`:

```yaml
  universe/external/rtklib_ros_bridge:
    type: git
    url: https://github.com/MapIV/rtklib_ros_bridge.git
    version: ros2-v0.1.0
  universe/external/llh_converter:
    type: git
    url: https://github.com/MapIV/llh_converter.git
    version: ros2
```

These are missing in Edge.Auto's repos file.
